# Generated by Django 4.0.6 on 2022-07-12 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('works_list', '0002_firstlevel_secondlevel_rename_tasklist_zerolevel_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fifthlevel',
            old_name='zeroLevel',
            new_name='fourthLevel',
        ),
        migrations.RenameField(
            model_name='fourthlevel',
            old_name='zeroLevel',
            new_name='thirdLevel',
        ),
        migrations.RenameField(
            model_name='secondlevel',
            old_name='zeroLevel',
            new_name='firstLevel',
        ),
        migrations.RenameField(
            model_name='thirdlevel',
            old_name='zeroLevel',
            new_name='secondLevel',
        ),
    ]
