# Generated by Django 4.0.6 on 2022-07-15 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('works_list', '0004_test'),
    ]

    operations = [
        migrations.AddField(
            model_name='zerolevel',
            name='test',
            field=models.BooleanField(null=True),
        ),
    ]
