# Generated by Django 4.0.6 on 2022-07-15 20:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('works_list', '0005_zerolevel_test'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='zerolevel',
            name='test',
        ),
    ]
