# Generated by Django 4.0.6 on 2022-07-16 05:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('works_list', '0008_test'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Test',
        ),
    ]
